import assert from 'node:assert/strict';
import {readFileSync, statSync} from 'node:fs';
const read = path => readFileSync(new URL('../' + path, import.meta.url), 'utf8');
const home = read('index.html');
const css = read('css/home-training.css');
assert.ok(home.includes('css/home-training.css?v=20260930'));
assert.ok(home.includes('LB AeroFlight is<br><em>open for business.</em>'));
assert.ok(home.includes('Per hour + fuel'));
assert.ok(!/per flight|Albuquerque/i.test(home));
assert.ok(home.includes('Double Eagle<br> &amp; Moriarty'));
assert.equal((home.match(/<li><svg class="training-icon"/g)||[]).length,6);
assert.ok(css.includes('@media(max-width:1040px)'));
assert.ok(css.includes('a:focus-visible'));
assert.ok(css.includes('prefers-reduced-motion'));
for(const asset of ['lucky-13-training-hero.webp','lucky-13-team-flight.webp']) assert.ok(statSync(new URL('../assets/img/'+asset,import.meta.url)).size < 750000);
assert.ok(!home.includes('FULL HOMEPAGE DESIGN CONCEPT'));
console.log('PASS: approved training homepage, hourly rate, airports, six topics, responsive breakpoints, focus, reduced motion and optimized artwork');
